### ISSUE TITLE
Progress bar rise function is being executed at the load of the page

### ISSUE THREAD

**Issue by PyTanay** [alketaademaj/Vanilla_javascript_projects#1]
//making the skills bar go up
//get the class/element
var percentage_raise = document.getElementsByClassName('percentage');
//console.log(percentage_raise)
var bar = window.pageYOffset
if (document.documentElement.scrollTop >=710) {
    console.log("its working");
}

> You have to figure out a way to run this function when the element comes on page otherwise it will run when the page loads but elements will be out of screen and you won't see the animation!
@alketaademaj

**Comment by alketaademaj** [comment]
I fixed it you potato @PyTanay
